## YAML Template.
name: RunicSkyblock
author: runelynx
description: "Bukkit plugin for Runic Universe server."
main: io.github.runelynx.runicskyblock.RunicSkyblock
version: 0.1
commands:
   seeker:
      description: "Promote survival newbies"
      usage: /<command> [playername]
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   sbtest:
      description: "Testing stuff"
      usage: /<command>
   rankup:
      description: "Check for a promotion"
      usage: /<command>
   joindates:
      description: "Update all player join dates"
      usage: /<command>
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"